change labels() method return type
Llandy3d/pytheus pull request #58
Opened 2024-10-05 11:22 UTC by pradishb

fix #57

2024-10-10 20:10 UTC, Llandy3d requested changes
👋  hi, thanks a lot for catching this issue and the contribution!

Due to having to support older versions of python I think the best course of action would be to use the [typing_extensions](https://github.com/python/typing_extensions) library to make direct use of `Self`.

From my tests using `"Self"` would still mark it as `unknown` for pyright the returned object (although it fixes the error on the method).

Let me know if you want to work on it further or if you prefer for me to take over, regardless of choice I really appreciate you taking the time for raising and fixing this 🙌 

So to recap the course of action would be:
1. Add a dependency to typing_extensions
2. Import `Self` without the need for the `TYP_CHECKING` check
3. Replace `"Self"` -> `Self`

2024-10-10 20:10 UTC, Llandy3d commented on pytheus/metrics.py
> +    from typing import Self
I would skip this check and import directly a backward compatible backport 🤔

2024-10-10 20:10 UTC, Llandy3d commented on pytheus/metrics.py
> +    def labels(self, pytheus_labels_: Optional[Labels] = None, **kwargs: str) -> "Self":
If the suggestion from this review gets applied, I would remove the quotes and use directly `Self`

2024-10-15 16:24 UTC, pradishb commented
I agree that using typing_extensions is the better solution. I have made the requested changes,

2024-10-15 16:46 UTC, Llandy3d approved these changes
Looks good! 🙌 
Thank you for your contribution 🙇

2024-10-15 18:26 UTC, Llandy3d commented
it actually doesn't seem to be enough as the return type now mismatch 😭

2025-06-24 22:30 UTC, Llandy3d reviewed
Looks good!

I think that for completeness we should also align the typing for the mentioned classes, what do you think ?
Beside that looks great 🙌

2025-06-24 22:30 UTC, Llandy3d commented on pytheus/metrics.py
> +        collector: Optional[_MetricCollector[Self]] = None,
this needs to be changed also for the `Histogram` and `Summary` class 🤔

2025-06-26 22:13 UTC, merged